name: PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  # Support for "docker push"
  docker-push:
    if: (contains(github.event.comment.body, 'docker push') || contains(github.event.comment.body, 'deploy rise')) && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: ':eyes: Acknowledge'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }, payload  } = context;
            github.issues.updateComment({
              owner,
              repo,
              comment_id: payload.comment.id,
              body: ':whale: building docker image...',
            });
      # this is needed because the comment-events does not include the information about the commit sha
      # taken from https://github.com/actions/checkout/issues/331
      - name: Get PR
        uses: actions/github-script@v3
        id: get-pr
        with:
          script: |
            const request = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            }
            core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
            try {
              const result = await github.pulls.get(request)
              return result.data
            } catch (err) {
              core.setFailed(`Request failed with error ${err}`)
            }
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }}

      - name: ':+1: Mark as done'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo }, payload  } = context;
            const result = await github.pulls.get({ repo, owner, pull_number: issue_number });
            const sha = result.data.head.sha;
            github.issues.updateComment({
              owner,
              repo,
              comment_id: payload.comment.id,
              body: `:whale: Pushed docker image eu.gcr.io/tradeshift-base/${repo}:${sha}`,
            });
